//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CORONAVIRUS_PERUEntities : DbContext
    {
        public CORONAVIRUS_PERUEntities()
            : base("name=CORONAVIRUS_PERUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<REGISTROS> REGISTROS { get; set; }
    
        public virtual ObjectResult<R_ACTIVOS_HOSPI_UCI_Result> R_ACTIVOS_HOSPI_UCI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_ACTIVOS_HOSPI_UCI_Result>("R_ACTIVOS_HOSPI_UCI");
        }
    
        public virtual ObjectResult<R_INFEC_FALLE_RECUPE_Result> R_INFEC_FALLE_RECUPE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_INFEC_FALLE_RECUPE_Result>("R_INFEC_FALLE_RECUPE");
        }
    
        public virtual ObjectResult<R_INFEC_X_DIA_Result> R_INFEC_X_DIA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_INFEC_X_DIA_Result>("R_INFEC_X_DIA");
        }
    
        public virtual ObjectResult<Nullable<decimal>> R_PORCENTAJE_INFECTADOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("R_PORCENTAJE_INFECTADOS");
        }
    
        public virtual ObjectResult<Nullable<decimal>> R_PORCENTAJE_MORTALIDAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("R_PORCENTAJE_MORTALIDAD");
        }
    
        public virtual ObjectResult<R_PRUEBAS_ACTIVOS_HOSPIT_UCI_Result> R_PRUEBAS_ACTIVOS_HOSPIT_UCI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_PRUEBAS_ACTIVOS_HOSPIT_UCI_Result>("R_PRUEBAS_ACTIVOS_HOSPIT_UCI");
        }
    
        public virtual ObjectResult<R_PRUEBAS_CASOSACTIVOS_Result> R_PRUEBAS_CASOSACTIVOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_PRUEBAS_CASOSACTIVOS_Result>("R_PRUEBAS_CASOSACTIVOS");
        }
    
        public virtual ObjectResult<SP_LISTADOGENERAL_Result> SP_LISTADOGENERAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTADOGENERAL_Result>("SP_LISTADOGENERAL");
        }
    }
}
